---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gitlab.name" . }}-config-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.config_pvc_size }}
  volumeName: {{ template "gitlab.name" . }}-lab-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gitlab.name" . }}-logs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.logs_pvc_size }}
  volumeName: {{ template "gitlab.name" . }}-logs-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gitlab.name" . }}-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.data_pvc_size }}
  volumeName: {{ template "gitlab.name" . }}-data-pv
