apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.name" . }}
  labels:
    app: {{ template "gitlab.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  - name: gitlab
    port: 443
    targetPort: 443
  - name: registry
    port: 446
    targetPort: 446
  selector:
    app: {{ template "gitlab.name" . }}
