apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.name" . }}
  labels:
    app: {{ template "gitlab.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: ssh
    port: {{ .Values.sshPort | int }}
    targetPort: ssh
  - name: https
    port: {{ .Values.httpsPort | int }}
    targetPort: http
  - name: registry
    port: {{ .Values.registryPort | int }}
    targetPort: registry
  selector:
    app: {{ template "gitlab.name" . }}
